import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <span className="brand">mini-survey</span>!
        </h1>
        <p>
          This project is a work in progress. At this point the editor view is
          fully functional:
        </p>
        <button
          onClick={() => {
            router.push("/edit/");
          }}
        >Edit</button>
      </main>
    </>
  );
}
